"""bang

Revision ID: 3628820fc4b2
Revises: 
Create Date: 2022-08-08 19:27:52.681534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3628820fc4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('slist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slist_id'], ['shopping_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_item_name'), 'shopping_list_item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_item_name'), table_name='shopping_list_item')
    op.drop_table('shopping_list_item')
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
