"""added note

Revision ID: dae1402a4932
Revises: d24befb1c0ed
Create Date: 2023-05-25 22:55:27.549236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae1402a4932'
down_revision = 'd24befb1c0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'note')
    # ### end Alembic commands ###
